### PR TITLE
Fixed check banners restriction

### PR DESCRIPTION
**Pull request by fafranco82**

### CODE REVIEW

**Comment by Alsciende** [comment]
You can look at 574ec93ad1a4777c72b840c10ab0b3a5f34079d1, I fixed the issue already, and I added a few useful methods to SlotCollectionDecorator.

**Comment by Alsciende** [comment]
Also, thanks to SlotCollectionProviderInterface, all decks and decklists are automatically known as having a getSlots() method which returns a SlotCollectionInterface, so method name completion is working well.

**Comment by Alsciende** [comment]
I really don't know why I didn't do this earlier...

**Comment by fafranco82** [comment]
I see. Very clever, and very useful methods on SlotCollectionInterface.

**Pull request closed without merging**
