### PR TITLE
Removed functional-php libray and replaced with proper Doctrine functions

### PR DESCRIPTION
**Pull request by fafranco82**
After a little bit investagion I found out that Doctrine AraryCollection has useful functional methods, so I replaced functional-php fucntions with Doctrine ones.

### CODE REVIEW

**Comment by Alsciende** [comment]
So much better!

**Comment by Alsciende** [comment]
It looks like you forgot 3 occurences of Functional in DeckValidationHelper.

**Comment by fafranco82** [comment]
Very true, I'm so sorry. I've already created a new PR with a tested fix

**Comment by Alsciende** [comment]
argh I was already on it

**Comment by fafranco82** [comment]
I'm very fast, man, XD. Nah, I was at home with free time to fixed it up quickly. I know how to do it, it was my fault, so I quickly fixed it ;)

**Pull request merged**
