### PR TITLE
I18N work

### PR DESCRIPTION
**Pull request by fafranco82**
Added toString() methods to `Faction` and `Type` entities, which `app:import:std` command requires, and added `is_primary` to the mandatory fields of `Faction` entity in order to import it.

### CODE REVIEW

**Comment by fafranco82** [comment]
I18N work in progress:

* DoctrineExtensions Translatable configuration
* Repositories for all translatable entities
* New command `app:import:trans` to import translations from json data repository
* New I18N routes: only for locales that not are the default, `en`, so decklist are in `/decklists` for English and `/es/decklist` for Spanish. API routes doesn't change for backward compatibility with current users. But the site internally use `?_locale=es` if the `locale` is not `en`
* The format chosen for translations files was YAML because the translations would not be done by professional translators and YAML is more programmer-friendly (to edit en plain text).
* The path for image has change to `bundle/cards/<locale>/<code>.<ext>`, so current english pictures must be moved to `en` subdirectory.

**Comment by Alsciende** [comment]
Thank you for your awesome work!

I merged to branch 'i18n'.

I want the locales to be accessible from a subdomain, not a subpath. So a spanish decklist would be at http://es.thronesdb.com/decklist/view/111 instead of http://thronesdb.com/decklist/view/111, which is an alias for http://en.thronesdb.com/decklist/view/111

**Comment by Alsciende** [comment]
I don't think I'm going to support spanish images. There's no official repository for these images, AFAIK. So updating is a pain and is totally dependent on your work, availability and good will.

**Comment by Alsciende** [comment]
Regarding the URL, I had set up the service src/AppBundle/Listener/LocalePrefixListener.php to handle the locale in the subdomain. I'm not sure what to do with JMSI18nRoutingBundle, then.

**Comment by fafranco82** [comment]
Well, the I18N sites on subdomains is easy, only change one line in `config.yml`, in the `jms_i18n_routing` entry (see http://jmsyst.com/bundles/JMSI18nRoutingBundle/master/configuration).

About images, I have all of them scanned by me (I used them to make an OCTGN image pack), so the only problem with spanish cards would be the server space, or how to upload them to the server (I noticed that image cards aren't in the repo, I suppose you fetch them directly on server with symfony command, or direct upload by FTP).

**Comment by fafranco82** [comment]
I haven't seen that Listener... looking at it, I think jms_i18n_routing is unnecesary, I will remove it then. Then only drawback is that I have to work with fake domains in my `hosts` file, but I can live with it :)

**Comment by Alsciende** [comment]
Thank you again for your awesome work!

The bundle can indeed be configured to use different hosts for different locales. I don't like the fact that I have to hard-code the domain name in the configuration, though. My Listener was a bit better in this regard, because it worked for any domain name.

Anyway, I was able to set it up with this configuration:

```
jms_i18n_routing:
    default_locale: %default_locale%
    locales: %supported_locales%
    strategy: custom
    hosts:
        en: "%website_url%"
        es: "es.%website_url%" 
    redirect_to_host: true
```

Regarding the images, the issue I faced earlier was with the "continuity of service". Right now, you have the spanish images. You scanned, cropped, converted all the images in a long and boring process. I know, I did it before FFG started publishing good images on CGDB ;) But what about in 1, 2, or 3 years? Translating is already a time-consuming task. I'm not ready to take that risk.

One aspect of this is that I have to provide a fallback in case the localized image isn't available. So I have to read the filesystem every time I send the url of an image. If the localized image is in the filesystem, I send its url, otherwise I send the fallback (english). Those filesystem accesses are draining the server resources.

Frankly, I've tried to make it work for NetrunnerDB for years, and in the end it was too much work and maintenance for too small a result.

**Comment by Alsciende** [comment]
> I haven't seen that Listener... looking at it, I think jms_i18n_routing is unnecesary, I will remove it then. Then only drawback is that I have to work with fake domains in my hosts file, but I can live with it :)

That would be nice, but my question is: can you make the Locale Switcher work with my Listener?

**Comment by fafranco82** [comment]
I have being doing tests:

* Without `jms_i18n_routing` and using only your Listener, all works fine, but, as you said, the locale switcher needs some tricky changes to work
* Configuring properly `jms_i18n_routing` and commenting out the listener body, all works fine, too. And the locale switcher still works.

Whichever approach was selected, I noticed that the setting locale by subdomain fixed several problems I face with url prefixing:

* All url generated with fos_routing, that doesn't take into account the current locale to generate URLs... but with subdomains, the URL generated, as it is relative, maintains the subdomain and thus the locale. It needs a patch that I can remove it now.
* API calls: the same as above.

So the subdomain approach to change locale seems to be very, very brilliant.

**Comment by fafranco82** [comment]
About images, I can assure and swart that, as long as I'm playing GoT, I will scans and translated files. It takes me only a couple of hours and it is a work I'm proud to have done it. But I cannot assure I'll be playing this game until its end... my intention is to do it, but nothing in life is sure...

I understand you with the image fallback problem... one solution could be copying by default english card in the localized folder, removing the double disk access in case the locale card image doen't exist.

**Comment by Alsciende** [comment]
Good. That's perfect. I'm going to remove my Listener and use exclusively I18nRoutingBundle. It's really good work :) 

I'm going to move your work on the localized images to a new branch, and I'll think about it.

**Comment by fafranco82** [comment]
Perfect.

Now I have doubts about how to continue with work. All of these commits were merged into a `i18n` as you said, although I don't see that on the PR history... 

And then you have done some changes on that branch... Maybe I must pull i18n branch on my local copy (from upstream), pushing to my forked copy on github, and continue with the work from there?

Sorry, I'm a github newbie, hehehe

**Comment by Alsciende** [comment]
I did a checkout your branch, so unless you just did some work on it, my i18n branch is simply ahead of you. You can do a checkout on it, and git will do a fast-forward.

**Comment by Alsciende** [comment]
And once your local repository is ok, you can push on Github, sure.

**Comment by Alsciende** [comment]
Hmm... I merged i18n into master, and I deleted i18n. So, actually, your commits are now merged into master.

**Pull request merged**
