### PR TITLE
Implement rules for The Conclave

### LINKED ISSUE #149: Implement 'The Conclave' special deckbuilding rules
http://thronesdb.com/card/09045

### PR DESCRIPTION
**Pull request by ystros**
Resolves #149

### CODE REVIEW

**Comment by Alsciende** [comment]
Thank you!

**Comment by ystros** [comment]
Thanks for merging and deploying!

I think you need to run the following to update the translation files client side (at least I did locally while developing). While the server side validation is working now on the site, the client side validation + card filtering is failing because the translation for `Translator.trans('card.traits.maester')` is missing.

```
php app/console bazinga:js-translation:dump
```

**Comment by ystros** [comment]
Nevermind, it seems like it got updated as I wrote this comment (or maybe something was aggressively cached on my end). Sorry for the hassle.

Thanks again!

**Comment by Alsciende** [comment]
Thanks!

**Pull request merged**
