### PR TITLE
Check conditions for Kings of Summer, Kings of Winter and Rains of Castamere agendas

### PR DESCRIPTION
**Pull request by fafranco82**

### CODE REVIEW

**Comment by fafranco82** [comment]
Also, check restrictions in PHP when saving deck.

To make it easy, I added the Functional PHP library, to use it when checking restrictions.

**Comment by Alsciende** [comment]
This library is awesome!

**Comment by Alsciende** [comment]
Ok, I'm trusting you blindly. I'm putting it online without testing. YOLO

**Comment by Alsciende** [comment]
> lstrojny/functional-php 1.2.4 requires php >=5.6.0

argh

**Comment by fafranco82** [comment]
What version of PHP used the server? 

I've looking in the composer repository, and v1.0 of functional-php only require PHP >= 5.3,,, but I don't sure the only 3 functions I use (map, select and reduce) will work well. I will try with that version.

**Comment by fafranco82** [comment]
It seemd that work well with v1.0 of functional-php. What do you prefer? Upgrade php version if its possible, or downgrade functional-php?

**Comment by Alsciende** [comment]
The server uses php-5.5.9.

We can use functional-php 1.0, or we can remove it entirely. It's nice, but it's nothing that can't be done easily with `array_map`, `array_reduce`, `array_filter`, etc.

Sorry, but I'm not going to update to php-5.6, because it is not a package officially supported by Ubuntu 14.04 (and probably never will).

**Comment by Alsciende** [comment]
So, with the help of 20e34b4fabca353c0eabaaa51347b87045fde1cb, the fix is online.

**Pull request merged**
